#!/bin/bash

# Include common functions
dir="${BASH_SOURCE%/*}"
if [[ ! -d "$dir" ]]; then dir="$PWD"; fi
. "$dir/common.sh"

sub 1.1.1
sub 1.1.1 1.1.2
sub 1.1.1 1.1.2 1.1.3
sub 1.1.*
sub 2.*
sub 3.* 2.* 1.*

sleep 1

pub 1.1.1 1.1.2 1.1.3
pub 2.1.1 1.1.4
pub 2.1.1 3.1.1
pub 2.1.1 1.1.4 3.1.1
pub 3.2 2.3

sleep 2

cleanup
