#!/bin/bash

# Include common functions
dir="${BASH_SOURCE%/*}"
if [[ ! -d "$dir" ]]; then dir="$PWD"; fi
. "$dir/common.sh"

sub -m -l 35000 1.1
sleep 1
sub -p 35000 -l 35001 2.1
sleep 1
sub -p 35001 -l 35002 3.1
sleep 1
sub -p 35002 "+.1"
sleep 1

pub 1.1 2.1 3.1 4.1

sleep 2

assert_no_errors
expect_pubs_received 4 1.1 2.1 3.1 4.1
