#!/bin/bash

# Include common functions
dir="${BASH_SOURCE%/*}"
if [[ ! -d "$dir" ]]; then dir="$PWD"; fi
. "$dir/common.sh"

for S in $(seq 0 2); do
    reset_logs
    sub -x $S $S
    sleep 1
    for P in $(seq 0 2); do
	pub -x $P -a $S
	sleep 2
    done
    assert_no_errors
    if [[ $S -eq 0 ]]; then
	expect_pubs_received 1 $S
	expect_acks_received 1
    else
	expect_pubs_received 2 $S
	expect_acks_received 2
    fi
done
