#!/bin/bash

# Include common functions
dir="${BASH_SOURCE%/*}"
if [[ ! -d "$dir" ]]; then dir="$PWD"; fi
. "$dir/common.sh"

sub -w 1 -l 40000 -s X -s A
sub -w 1 -l 40001 -p 40000 -s X -s B
sub -w 1 -l 40002 -p 40001 -s X -s C
sub -w 1 -l 40003 -p 40002 -s X -s D
sub -w 1 -l 40004 -p 40003 -s X -s E
sub -w 1 -l 40005 -p 40004 -s X -s F
sub -w 1 -l 40006 -p 40005 -s X -s G
sub -w 1 -l 40007 -p 40006 -s X -s H
sub -w 1 -l 40008 -p 40007 -s X -s I
sub -w 1 -l 40009 -p 40008 -s X -s J
sub -w 1 -l 40010 -p 40009 -s X -s K

# Link to all nodes in chain

sub -w 2 -l 40011 -p 40000 -p 40001 -p 40002 -p 40003 -p 40004 -p 40005 -p 40006 -p 40007 -p 40008 -p 40009 -p 40010 -s X -s L
sub -w 2 -l 39999 -p 40010 -p 40009 -p 40008 -p 40007 -p 40006 -p 40005 -p 40004 -p 40003 -p 40002 -p 40001 -p 40000 -s X -s M
sub -w 2 -l 40012 -p 40008 -p 40007 -p 40004 -p 40006 -p 40010 -p 40000 -p 40002 -p 40009 -p 40005 -p 40003 -p 40001 -s X -s N

sleep 4

pub -p 39999 A B C D E F G H I J K L M N
pub -p 40000 A B C D E F G H I J K L M N
pub -p 40001 A B C D E F G H I J K L M N
pub -p 40002 A B C D E F G H I J K L M N
pub -p 40003 A B C D E F G H I J K L M N
pub -p 40004 A B C D E F G H I J K L M N
pub -p 40005 A B C D E F G H I J K L M N
pub -p 40006 A B C D E F G H I J K L M N
pub -p 40007 A B C D E F G H I J K L M N
pub -p 40008 A B C D E F G H I J K L M N
pub -p 40009 A B C D E F G H I J K L M N
pub -p 40010 A B C D E F G H I J K L M N
pub -p 40011 A B C D E F G H I J K L M N
pub -p 40012 A B C D E F G H I J K L M N

sleep 1

expect_pubs_received 196 A B C D E F G H I J K L M N

# Reachability check

pub -p 40005 X

sleep 1

assert_no_errors
expect_pubs_received 14 X
