#!/bin/sh

killall registry
killall reg_subs


# Start the registry service

build/dist/bin/registry&
sleep 1

# Start some subscribers

build/dist/bin/reg_subs a/b/c&
build/dist/bin/reg_subs a/b/c&
build/dist/bin/reg_subs a/b/c&
build/dist/bin/reg_subs a/b/c&
build/dist/bin/reg_subs a/b/c&
build/dist/bin/reg_subs a/b/c&
build/dist/bin/reg_subs a/b/c&
build/dist/bin/reg_subs a/b/c&
build/dist/bin/reg_subs a/b/c&
build/dist/bin/reg_subs a/b/c&
build/dist/bin/reg_subs a/b/c&
build/dist/bin/reg_subs a/b/c&
build/dist/bin/reg_subs a/b/c&
build/dist/bin/reg_subs a/b/c&
build/dist/bin/reg_subs a/b/c&
build/dist/bin/reg_subs 1/2/3&
build/dist/bin/reg_subs "+/+/#"&

sleep 1
build/dist/bin/reg_pubs a/b/c --msg hello
build/dist/bin/reg_pubs 1/2/3 --msg world
