#!/bin/bash

# Include common functions
dir="${BASH_SOURCE%/*}"
if [[ ! -d "$dir" ]]; then dir="$PWD"; fi
. "$dir/common.sh"

py_retained_pub
sleep 1

py_late_sub
sleep 2

assert_no_errors
expect_pubs_received 1 a/b/c
