#!/bin/bash

# Include common functions
dir="${BASH_SOURCE%/*}"
if [[ ! -d "$dir" ]]; then dir="$PWD"; fi
. "$dir/common.sh"

js_sub_ks
sleep 1

js_pub_ks
sleep 1

assert_no_errors
expect_pubs_received 2 a/b/c

#
# Verify interop between C sub and javascript pub
#
reset_logs

sub a/b/c
sleep 1

js_pub_ks
sleep 1

assert_no_errors
expect_pubs_received 2 a/b/c

reset_logs

sub -x 2 a/b/c
sleep 1

js_pub_ks -x 2
sleep 1

assert_no_errors
expect_pubs_received 2 a/b/c

#
# Verify interop between javascript pub and C sub
#
reset_logs

js_sub_ks
sleep 1

pub a/b/c
sleep 2

assert_no_errors
expect_pubs_received 1 a/b/c

reset_logs

js_sub_ks -x 2
sleep 1

pub -x 2 a/b/c
sleep 2

assert_no_errors
expect_pubs_received 1 a/b/c
