#!/bin/bash

# Include common functions
dir="${BASH_SOURCE%/*}"
if [[ ! -d "$dir" ]]; then dir="$PWD"; fi
. "$dir/common.sh"

cleanup

sub -w 1 -l 50000  T
sub -w 1 -l 40000 -p 50000 A
sub -w 1 -l 30000 -p 50000 B

pub -w 2 -b -p 30000 A
pub -w 2 -b -p 40000 B
