#!/bin/bash

# Include common functions
dir="${BASH_SOURCE%/*}"
if [[ ! -d "$dir" ]]; then dir="$PWD"; fi
. "$dir/common.sh"

#
#           /---> B ----\
#          /             \
#         /               \
#       A ------> C -------> E
#         \               /
#          \             /
#           \---> D-----/
#
#

cleanup

sub -l 40000 E
sleep 1

sub -l 40001 -p 40000 B
sub -l 40002 -p 40000 C
sub -l 40003 -p 40000 D

sleep 1
sub -l 40004 -p 40001 -p 40002 -p 40003 A

sleep 1
