#!/usr/bin/perl
#
# ./build/test/bin/fuzzer ./crash-f15bb0b64b75838dc982cef11b0c3b9ea08fcec6 2>&1 | ./tools/asan_addr2line
#

while (<>) {
    if (/(.*#[0-9]+ 0x[0-9a-f]+  )\((.*)\+(0x[0-9a-f]+)\)/) {
	$name = $2;
	$addr = $3;
	$line = `addr2line -e $name $addr`;
	chomp($line);
	if ($line eq "??:?") {
	    print $_;
	} else {
	    print "$1($line)\n";
	}
    } else {
	print $_;
    }
}
