#!/bin/bash

echo LIBRARY dps_shared
echo
echo EXPORTS
echo
grep -hv '^$' inc/dps/*.h | grep -v '^ ?*' | grep -v '^/' | grep -v '^#' | grep -v '^typedef'  | grep -v '^}' | grep -v '^struct' | grep -v 'extern "C"'  | cut -d'(' -f1 | sed 's/^.* DPS_/DPS_/' | sed -e 's/;//' | sort
