#!/bin/sh
#
# run all existing corpus to check for errors
#
# example:
# $ scons ... transport=fuzzer
# $ ./fuzzer_check
# $ scons ... transport=dtls
# $ USE_DTLS=1 ./fuzzer_check
#

USE_DTLS=${USE_DTLS:-0}

if [ $USE_DTLS -eq 0 ]; then
    find test/corpus/cbor -type f | xargs ./build/test/bin/cbor_fuzzer
    if [ $? -ne 0 ]; then
	exit 1;
    fi
    find test/corpus/multicast_receive -type f | xargs ./build/test/bin/multicast_receive_fuzzer
    if [ $? -ne 0 ]; then
	exit 1;
    fi
    find test/corpus/unicast_receive -type f | xargs ./build/test/bin/net_receive_fuzzer
    if [ $? -ne 0 ]; then
	exit 1;
    fi
fi

if [ $USE_DTLS -ne 0 ]; then
    for step in {0..6}; do
	find test/corpus/dtls_server_$step -type f | xargs ./build/test/bin/dtls_fuzzer server $step
	if [ $? -ne 0 ]; then
	    exit 1;
	fi
    done
    for step in {0..7}; do
	find test/corpus/dtls_client_$step -type f | xargs ./build/test/bin/dtls_fuzzer client $step
	if [ $? -ne 0 ]; then
	    exit 1;
	fi
    done
fi
