#!/bin/bash

OPTIND=1

engine="fdp"
outfile=''
logfile="log"
num_subs=1
num_kills=0
debug=''

while getopts "de:hk:l:o:s:" opt; do
    case "$opt" in
    d)  debug="-d"
        ;;
    e)  engine=$OPTARG
        ;;
    h)  echo "[-d] [-o <png file>] [-l <logfile>] [-k count] [-s <count>] [-e <engine>] <mesh-file>"
        exit 0
        ;;
    k)  num_kills=$OPTARG
        ;;
    l)  logfile=$OPTARG
        ;;
    o)  outfile=$OPTARG
        ;;
    s)  num_subs=$OPTARG
        ;;
    esac
done

shift $((OPTIND-1))

if [[ $outfile != '' ]]; then
    build/test/bin/make_mesh $debug -s $num_subs -k $num_kills -f $@ 2> $logfile | $engine -Tpng > $outfile
    display $outfile&
else
    build/test/bin/make_mesh $debug -s $num_subs -k $num_kills -f $@ 2> $logfile | $engine -Tpng | display &
fi
